### ISSUE TITLE
https://www.driveandact.com/  this web need User name and password

### ISSUE THREAD

**Issue by MachineLearning11** [Simael/zs-drive_and_act#1]
can you give some information about User name and password

**Comment by Simael** [comment]
I can share this information with you privately if you contact me by e-mail.

**Comment by MachineLearning11** [comment]
Thank you very much for your reply. I really need the RGB related data set of drive and act. My email is ***@***.*** , thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Simael/zs-drive_and_act"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月6日(星期三) 晚上6:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Simael/zs-drive_and_act] https://www.driveandact.com/  this web need User name and password (Issue #1)



 I can share this information with you privately if you contact me by e-mail.

**Comment by Simael** [comment]
Please write a mail directly to my e-mail address so i can reply, find my e-mail information in the linked paper of this repository.
